version: '2.1'

services:

  ldl-dev:
    container_name: "ldl-dev"
    image: ldl-dev
    build:
       context: ./docker
       args:
          EDIT_USER: ${EDIT_USER}
          EDIT_GROUP: ${EDIT_GROUP}
    volumes:
      - ./docker/etc/bashrc:/root/.bashrc
      - ./docker/bin:/docker/bin
      - ./.env:/etc/environment
      - .:/ldl-dev-tools
      - ./docker/usr/share/ldl_bash_utils:/usr/share/ldl_bash_utils
      - ./docker/usr/share/git:/usr/share/git
      - ./docker/etc/bashrc:/home/ldl/.bashrc
      - ./docker/etc/motd:/etc/motd
      - ./docker/github:/etc/github
      - ./bin:/ldl
      - ./docker/projects:/home/ldl/projects
      - ${EDIT_USER_HOME}/.ssh:/home/ldl/.ssh
    environment:
       - EDIT_USER=${EDIT_USER}
       - EDIT_GROUP=${EDIT_GROUP}
       - EDIT_USER_HOME=${EDIT_USER_HOME}
       - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
       - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
