#!/bin/bash

source /usr/share/ldl_bash_utils

stdout_work "[LDL Pre commit] Attempting to normalize syntax ..."

echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="/ldl-dev-tools/vendor/bin/php-cs-fixer"

git status --porcelain | grep -e '^[ AM]\(.*\).php$' | cut -c 3- | while read line; do
    $PHP_CS_FIXER fix "$line" --diff --rules=@Symfony,\
-dir_constant,\
-ereg_to_preg,\
-error_suppression,\
-fopen_flag_order,\
-fopen_flags,\
-function_to_constant,\
-implode_call,\
-is_null,\
-modernize_types_casting,\
-native_constant_invocation,\
-native_function_invocation,\
-no_alias_functions,\
-no_homoglyph_names,\
-non_printable_character,\
-php_unit_construct,\
-php_unit_mock_short_will_return,\
-psr_autoloading,\
-self_accessor,\
-set_type_to_cast,\
-single_class_element_per_statement,\
-protected_to_private,\
-short_scalar_cast,\
-single_line_after_imports,\
-single_line_comment_style,\
-single_quote,\
-standardize_increment,\
-standardize_not_equals,\
-no_blank_lines_after_phpdoc,\
-no_blank_lines_after_class_opening,\
-increment_style;
        git add "$line";
done